modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "custom_crafting"
version = "0.1.0"
displayName = "custom crafting "
authors = "randomusert"
description = '''
a mod that adds custom crafting recipes with custom resources!
'''
#logoFile = ""

[[dependencies.custom_crafting]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custom_crafting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custom_crafting]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
